name: Android Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v4 သို့ ပြောင်းထားပါသည်
      - name: set up JDK 17
        uses: actions/setup-java@v4 # v4 သို့ ပြောင်းထားပါသည်
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build Debug APK
        run: chmod +x gradlew && ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4 # ဤနေရာတွင် v4 ပြောင်းသုံးမှ error ပျောက်ပါမည်
        with:
          name: Ayra-Official-APK
          path: app/build/outputs/apk/debug/app-debug.apk
          
